### PR TITLE
support incomplete credential-gets

### PR DESCRIPTION
**Pull request by kusma**
Git doesn't always provide the username and path when asking for a credential. So perhaps something like this can be useful for getting partial credentials?

### CODE REVIEW

**Comment by kusma** [comment]
OK, this wasn't completely ideal. First off, attrs was leaked. Second, in the case where the username wasn't passed, Git want's to know what the stored username was. So here's an updated version.

**Comment by kusma** [comment]
...Aaand, with this last commit, git-credential-gnomekeyring starts passing t0303-credential-external from git.git.

**Comment by pah** [comment]
There is another gnome-keyring Git credential helper (pah/git-credential-helper), which I'd like to merge with this one at some point and submit the "best" solution to the contrib/ part of git/git

I'm not sure, if deleting all matching entries is the correct solution?  My implementation currently only drops the first one (and still passes the t0303 test).

**Comment by kusma** [comment]
I would assume deleting all entries makes more sense than just deleting the first one. After all, it's done in response to an unsuccessful login. So why should we continue to have invalid credentials stored, even if they didn't happen to be the first one returned by the keyring?

**Comment by kusma** [comment]
There's been upstream gnome keyring support in git for quite some time now, no point in keeping this one open.

**Comment by shugo** [comment]
@kusma 
Sorry for the long delay.

I've added deprecation notice of the project in README.md.
Thanks anyway.

**Pull request closed without merging**
